### ISSUE TITLE
解析地址错误

### ISSUE THREAD

**Issue by Burial0268** [Suxiaoqinx/Bilibili_video#1]
### 问题描述

rt，当我输入某个地址的时候，他返回了一个错误的[url](https://cn-hljheb-dx-v-03.bilivideo.com/upgcxcode/24/44/749474424/749474424-1-208.mp4?e=ig8euxZM2rNcNbRBhWdVhwdlhWU1hwdVhoNvNC8BqJIzNbfq9rVEuxTEnE8L5F6VnEsSTx0vkX8fqJeYTj_lta53NCM=&uipk=5&nbs=1&deadline=1655571764&gen=playurlv2&os=bcache&oi=1363565328&trid=00000d19474db24146cb83b4bfcad655a243T&mid=0&platform=html5&upsig=72cbc6c5bba314d22e75933ae52d20c0&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&cdnid=3842&bvc=vod&nettype=0&bw=151271&orderid=0,1&logo=80000000)

貌似部分url会出现这个问题，而部分则不会。

### 环境

php7.4，cookies正确，使用腾讯云北京服务器

**Comment by Suxiaoqinx** [comment]
返回到的视频地址403的话 是B站官方部分直链开启了防盗链 
只需要替换xxx.bilivideo.com的为其他正常的地址即可

**Comment by Burial0268** [comment]
我目前重试了一下，所有视频都获取不了。不知道是不是cookies的问题…
cookies是只需要_uuid=XXXX-XXXXX-XXXXX这一部分吗？还是说全部cookies都要

另外，我觉得应该不是b站防盗链的问题。因为我测试了在相同url的情况下，我的解析不出来，而别人的（包括作者的）都能解析。

如果是cookies问题，希望能在readme里面写清是全部cookies还是部分cookies。

**Comment by Suxiaoqinx** [comment]
能否加个联系方式呢？

**Comment by Suxiaoqinx** [comment]
3074193836
Q
